// https://yarduon.com
export default {
  en: {
    EUR: "Euro",
    AED: "UAE Dirham",
    AFN: "Afghan Afghani",
    ALL: "Albanian Lek",
    AMD: "Armenian Dram",
    ANG: "Netherlands Antillian Guilder",
    AOA: "Angolan Kwanza",
    ARS: "Argentine Peso",
    AUD: "Australian Dollar",
    AWG: "Aruban Florin",
    AZN: "Azerbaijani Manat",
    BAM: "Bosnia and Herzegovina Mark",
    BBD: "Barbados Dollar",
    BDT: "Bangladeshi Taka",
    BGN: "Bulgarian Lev",
    BHD: "Bahraini Dinar",
    BIF: "Burundian Franc",
    BMD: "Bermudian Dollar",
    BND: "Brunei Dollar",
    BOB: "Bolivian Boliviano",
    BRL: "Brazilian Real",
    BSD: "Bahamian Dollar",
    BTN: "Bhutanese Ngultrum",
    BWP: "Botswana Pula",
    BYN: "Belarusian Ruble",
    BZD: "Belize Dollar",
    CAD: "Canadian Dollar",
    CDF: "Congolese Franc",
    CHF: "Swiss Franc",
    CLP: "Chilean Peso",
    CNY: "Chinese Renminbi",
    COP: "Colombian Peso",
    CRC: "Costa Rican Colon",
    CUP: "Cuban Peso",
    CVE: "Cape Verdean Escudo",
    CZK: "Czech Koruna",
    DJF: "Djiboutian Franc",
    DKK: "Danish Krone",
    DOP: "Dominican Peso",
    DZD: "Algerian Dinar",
    EGP: "Egyptian Pound",
    ERN: "Eritrean Nakfa",
    ETB: "Ethiopian Birr",
    FJD: "Fiji Dollar",
    FKP: "Falkland Islands Pound",
    FOK: "Faroese Króna",
    GBP: "Pound Sterling",
    GEL: "Georgian Lari",
    GGP: "Guernsey Pound",
    GHS: "Ghanaian Cedi",
    GIP: "Gibraltar Pound",
    GMD: "Gambian Dalasi",
    GNF: "Guinean Franc",
    GTQ: "Guatemalan Quetzal",
    GYD: "Guyanese Dollar",
    HKD: "Hong Kong Dollar",
    HNL: "Honduran Lempira",
    HRK: "Croatian Kuna",
    HTG: "Haitian Gourde",
    HUF: "Hungarian Forint",
    IDR: "Indonesian Rupiah",
    ILS: "Israeli New Shekel",
    IMP: "Manx Pound",
    INR: "Indian Rupee",
    IQD: "Iraqi Dinar",
    IRR: "Iranian Rial",
    ISK: "Icelandic Króna",
    JEP: "Jersey Pound",
    JMD: "Jamaican Dollar",
    JOD: "Jordanian Dinar",
    JPY: "Japanese Yen",
    KES: "Kenyan Shilling",
    KGS: "Kyrgyzstani Som",
    KHR: "Cambodian Riel",
    KID: "Kiribati Dollar",
    KMF: "Comorian Franc",
    KRW: "South Korean Won",
    KWD: "Kuwaiti Dinar",
    KYD: "Cayman Islands Dollar",
    KZT: "Kazakhstani Tenge",
    LAK: "Lao Kip",
    LBP: "Lebanese Pound",
    LKR: "Sri Lanka Rupee",
    LRD: "Liberian Dollar",
    LSL: "Lesotho Loti",
    LYD: "Libyan Dinar",
    MAD: "Moroccan Dirham",
    MDL: "Moldovan Leu",
    MGA: "Malagasy Ariary",
    MKD: "Macedonian Denar",
    MMK: "Burmese Kyat",
    MNT: "Mongolian Tögrög",
    MOP: "Macanese Pataca",
    MRU: "Mauritanian Ouguiya",
    MUR: "Mauritian Rupee",
    MVR: "Maldivian Rufiyaa",
    MWK: "Malawian Kwacha",
    MXN: "Mexican Peso",
    MYR: "Malaysian Ringgit",
    MZN: "Mozambican Metical",
    NAD: "Namibian Dollar",
    NGN: "Nigerian Naira",
    NIO: "Nicaraguan Córdoba",
    NOK: "Norwegian Krone",
    NPR: "Nepalese Rupee",
    NZD: "New Zealand Dollar",
    OMR: "Omani Rial",
    PAB: "Panamanian Balboa",
    PEN: "Peruvian Sol",
    PGK: "Papua New Guinean Kina",
    PHP: "Philippine Peso",
    PKR: "Pakistani Rupee",
    PLN: "Polish Złoty",
    PYG: "Paraguayan Guaraní",
    QAR: "Qatari Riyal",
    RON: "Romanian Leu",
    RSD: "Serbian Dinar",
    RUB: "Russian Ruble",
    RWF: "Rwandan Franc",
    SAR: "Saudi Riyal",
    SBD: "Solomon Islands Dollar",
    SCR: "Seychellois Rupee",
    SDG: "Sudanese Pound",
    SEK: "Swedish Krona",
    SGD: "Singapore Dollar",
    SHP: "Saint Helena Pound",
    SLE: "Sierra Leonean Leone",
    SLL: "Sierra Leonean Leone",
    SOS: "Somali Shilling",
    SRD: "Surinamese Dollar",
    SSP: "South Sudanese Pound",
    STN: "São Tomé and Príncipe Dobra",
    SYP: "Syrian Pound",
    SZL: "Eswatini Lilangeni",
    THB: "Thai Baht",
    TJS: "Tajikistani Somoni",
    TMT: "Turkmenistan Manat",
    TND: "Tunisian Dinar",
    TOP: "Tongan Pa'anga",
    TRY: "Turkish Lira",
    TTD: "Trinidad and Tobago Dollar",
    TVD: "Tuvaluan Dollar",
    TWD: "New Taiwan Dollar",
    TZS: "Tanzanian Shilling",
    UAH: "Ukrainian Hryvnia",
    UGX: "Ugandan Shilling",
    USD: "United States Dollar",
    UYU: "Uruguayan Peso",
    UZS: "Uzbekistani So'm",
    VES: "Venezuelan Bolívar Soberano",
    VND: "Vietnamese dồng",
    VUV: "Vanuatu Vatu",
    WST: "Samoan Tālā",
    XAF: "Central African CFA Franc",
    XCD: "East Caribbean Dollar",
    XDR: "Special Drawing Rights",
    XOF: "West African CFA franc",
    XPF: "CFP Franc",
    YER: "Yemeni Rial",
    ZAR: "South African Rand",
    ZMW: "Zambian Kwacha",
    ZWL: "Zimbabwean Dollar",
  },
  es: {
    EUR: "Euro",
    AED: "Dírham de Emiratos Árabes",
    AFN: "Afgani afgano",
    ALL: "Lek albanés",
    AMD: "Dram armenio",
    ANG: "Florín antillano neerlandés",
    AOA: "Kwanza angoleño",
    ARS: "Peso argentino",
    AUD: "Dólar australiano",
    AWG: "Florín arubeño",
    AZN: "Manat azerbaiyano",
    BAM: "Marco bosnioherzegovino",
    BBD: "Dólar barbadense",
    BDT: "Taka bangladesí",
    BGN: "Leva búlgara",
    BHD: "Dinar bareiní",
    BIF: "Franco burundés",
    BMD: "Dólar bermudeño",
    BND: "Dólar de Brunéi",
    BOB: "Peso boliviano",
    BRL: "Real brasileño",
    BSD: "Dólar bahameño",
    BTN: "Ngultrum butanés",
    BWP: "Pula botswanesa",
    BYN: "Rublo bielorruso",
    BZD: "Dólar beliceño",
    CAD: "Dólar canadiense",
    CDF: "Franco congoleño",
    CHF: "Franco suizo",
    CLP: "Peso chileno",
    CNY: "Renminbi chino",
    COP: "Peso colombiano",
    CRC: "Colón costarriqueño",
    CUP: "Peso cubano",
    CVE: "Escudo caboverdiano",
    CZK: "Corona checoslovaca",
    DJF: "Franco yibutiano",
    DKK: "Corona danesa",
    DOP: "Peso dominicano",
    DZD: "Dinar argelino",
    EGP: "Libra egipcia",
    ERN: "Nakfa de Eritrea",
    ETB: "Birr etíope",
    FJD: "Dólar fiyiano",
    FKP: "Libra malvinense",
    FOK: "Corona feroés",
    GBP: "Libra esterlina",
    GEL: "Lari georgiano",
    GGP: "Libra de Guernsey",
    GHS: "Cedi de Ghana",
    GIP: "Libra de Gibraltar",
    GMD: "Dalasi",
    GNF: "Franco de Guinea",
    GTQ: "Quetzal",
    GYD: "Dólar de Guyana",
    HKD: "Dólar de Hong Kong",
    HNL: "Lempira",
    HRK: "Kuna",
    HTG: "Gourde",
    HUF: "Forint húngaro",
    IDR: "Rupia indonesia",
    ILS: "Shekel israelí",
    IMP: "Libra manesa",
    INR: "Rupia india",
    IQD: "Dinar iraquí",
    IRR: "Rial iraní",
    ISK: "Corona islandesa",
    JEP: "Libra de Jersey",
    JMD: "Dólar de Jamaica",
    JOD: "Dinar jordano",
    JPY: "Yen japonés",
    KES: "Chelín keniano",
    KGS: "Som",
    KHR: "Riel camboyano",
    KID: "Dólar de Kiribati",
    KMF: "Franco comorano",
    KRW: "Won",
    KWD: "Dinar kuwaití",
    KYD: "Dólar caimán",
    KZT: "Tenge",
    LAK: "Kip",
    LBP: "Libra libanés",
    LKR: "Rupia de Sri Lanka",
    LRD: "Dólar liberiano",
    LSL: "Loti de Lesotho",
    LYD: "Dinar libio",
    MAD: "Dirham marroquí",
    MDL: "Leu",
    MGA: "Ariary malgache",
    MKD: "Denar",
    MMK: "Kyat",
    MNT: "Tugrik",
    MOP: "Pataca macanés",
    MRU: "Uguiya",
    MUR: "Rupia mauriciano",
    MVR: "Rufiyaa maldivo",
    MWK: "Kwacha",
    MXN: "Peso mexicano",
    MYR: "Ringgit",
    MZN: "Metical",
    NAD: "Dólar de Namibia",
    NGN: "Naira",
    NIO: "Oro de Córdoba",
    NOK: "Corona noruega",
    NPR: "Rupia nepalés",
    NZD: "Dólar neozelandés",
    OMR: "Rial omaní",
    PAB: "Balboa panameño",
    PEN: "Sol nuevo",
    PGK: "Kina",
    PHP: "Peso filipino",
    PKR: "Rupia paquistaní",
    PLN: "Zloty",
    PYG: "Guaraní",
    QAR: "Rial katarí",
    RON: "Leu",
    RSD: "Dinar serbio",
    RUB: "Rublo ruso",
    RWF: "Franco ruandés",
    SAR: "Rial saudí",
    SBD: "Dólar de Salomon",
    SCR: "Rupia de Seychelles",
    SDG: "Libra sudanés",
    SEK: "Corona sueca",
    SGD: "Dólar de Singapur",
    SHP: "Libra de St-Helena",
    SLE: "Sierra leonean leones",
    SLL: "Sierra leonean leones",
    SOS: "Chelín somalí",
    SRD: "Dólar de Suriname",
    SSP: "Libra sursudanesa",
    STN: "Dobra santotomense",
    SYP: "Libra siria",
    SZL: "Lilangeni swazi",
    THB: "Baht tailandés",
    TJS: "Somoni",
    TMT: "Manat",
    TND: "Dinar tunecino",
    TOP: "Pa'anga",
    TRY: "Lira turca",
    TTD: "Dólar de Trinidad and Tobago",
    TVD: "Dólar de Tuvalu",
    TWD: "Dólar nuevo taiwanés",
    TZS: "Chelín de Tanzania",
    UAH: "Hrywnja",
    UGX: "Chelín de Uganda",
    USD: "Dólar estadounidense",
    UYU: "Peso uruguayo",
    UZS: "Sum uzbeko",
    VES: "Bolívar venezolano",
    VND: "Dong",
    VUV: "Vatu",
    WST: "Tala",
    XAF: "Franco centroafricano",
    XCD: "Dólar del Caribe Oriental",
    XDR: "Derechos especiales de giro",
    XOF: "Franco de África Occidental",
    XPF: "Franco del Pacífico",
    YER: "Rial yemení",
    ZAR: "Rand sudafricano",
    ZMW: "Kwacha de Zambia",
    ZWL: "Dólar de Zimbabue",
  },
  fr: {
    EUR: "Euro",
    AED: "Dirham arabe",
    AFN: "Afghani",
    ALL: "Lek",
    AMD: "Dram",
    ANG: "Florin des Antilles",
    AOA: "Kwanza",
    ARS: "Peso argentin",
    AUD: "Dollar australien",
    AWG: "Florin",
    AZN: "Manat",
    BAM: "Mark convertible",
    BBD: "Dollar barbadien",
    BDT: "Taka",
    BGN: "Lev bulgare",
    BHD: "Dinar bahreïni",
    BIF: "Franc burundais",
    BMD: "Dollar des Bermudes",
    BND: "Dollar Brunei",
    BOB: "Boliviano",
    BRL: "Réal brésilien",
    BSD: "Dollar des Bahamas",
    BTN: "Ngultrum",
    BWP: "Pula",
    BYN: "Rouble biélorusse",
    BZD: "Dollar du Belize",
    CAD: "Dollar canadien",
    CDF: "Franc congolais",
    CHF: "Franc suisse",
    CLP: "Peso chilien",
    CNY: "Yuan Renminbi",
    COP: "Peso colombien",
    CRC: "Colón",
    CUP: "Peso cubain",
    CVE: "Escudo cap-verdien",
    CZK: "Couronne tchèque",
    DJF: "Franc djiboutien",
    DKK: "Couronne danois",
    DOP: "Peso dominicain",
    DZD: "Dinar algérien",
    EGP: "Livre égyptien",
    ERN: "Nakfa",
    ETB: "Birr",
    FJD: "Dollar fidjien",
    FKP: "Livre falconian",
    FOK: "Couronne féroïen",
    GBP: "Livre sterling",
    GEL: "Lari géorgien",
    GGP: "Livre de Guernesey",
    GHS: "Cedi ghanéen",
    GIP: "Livre de Gibraltar",
    GMD: "Dalasi",
    GNF: "Franc guinéen",
    GTQ: "Quetzal",
    GYD: "Dollar de Guyana",
    HKD: "Dollar de Hong Kong",
    HNL: "Lempira",
    HRK: "Kuna",
    HTG: "Gourde",
    HUF: "Forint hongrois",
    IDR: "Rupiah indonésien",
    ILS: "Shekel israélien",
    IMP: "Livre de l'île de Man",
    INR: "Roupie indien",
    IQD: "Dinar irakien",
    IRR: "Rial iranien",
    ISK: "Couronne islandais",
    JEP: "Livre sterling de Jersey",
    JMD: "Dollar",
    JOD: "Dinar",
    JPY: "Yen",
    KES: "Shilling",
    KGS: "Som",
    KHR: "Riel cambodgien",
    KID: "Dollar kiribatan",
    KMF: "Franc comorien",
    KRW: "Won",
    KWD: "Dinar koweïtien",
    KYD: "Dollar Caïman",
    KZT: "Tenge",
    LAK: "Kip",
    LBP: "Livre libanais",
    LKR: "Roupie sri lankaise",
    LRD: "Dollar libérien",
    LSL: "Loti du Lesotho",
    LYD: "Dinar",
    MAD: "Dirham",
    MDL: "Leu",
    MGA: "Ariary malgache",
    MKD: "Denier macédonien",
    MMK: "Kyat",
    MNT: "Tugrik",
    MOP: "Pataca de Macao",
    MRU: "Ouguiya",
    MUR: "Roupie mauricien",
    MVR: "Rufiyaa maldivien",
    MWK: "Kwacha",
    MXN: "Peso mexicain",
    MYR: "Ringgit",
    MZN: "Metical",
    NAD: "Dollar namibien",
    NGN: "Naira",
    NIO: "Oro de Cordoue",
    NOK: "Couronne norvégien",
    NPR: "Roupie népalais",
    NZD: "Dollar néo-zélandais",
    OMR: "Rial omani",
    PAB: "Balboa panaméen",
    PEN: "Sol nuevo",
    PGK: "Kina",
    PHP: "Peso philippin",
    PKR: "Roupie pakistanais",
    PLN: "Zloty",
    PYG: "Guaraní",
    QAR: "Rial qatarien",
    RON: "Leu",
    RSD: "Dinar serbe",
    RUB: "Rouble russe",
    RWF: "Franc rwandais",
    SAR: "Rial saoudien",
    SBD: "Dollar salomonique",
    SCR: "Roupie seychellois",
    SDG: "Livre soudanais",
    SEK: "Couronne suédois",
    SGD: "Dollar de Singapour",
    SHP: "Livre de Sainte-Hélène",
    SLE: "Leone",
    SLL: "Leone",
    SOS: "Shilling somalien",
    SRD: "Dollar surinamais",
    SSP: "Livre",
    STN: "Dobra",
    SYP: "Livre syrien",
    SZL: "Lilangeni swazi",
    THB: "Baht thaïlandais",
    TJS: "Somoni",
    TMT: "Manat",
    TND: "Dinar",
    TOP: "Pa'anga",
    TRY: "Livre turque",
    TTD: "Dollar de Trinité-et-Tobago",
    TVD: "Dollar de Tuvalu",
    TWD: "Dollar taïwanais",
    TZS: "Shilling tanzanien",
    UAH: "Hrywnja",
    UGX: "Shilling ougandais",
    USD: "Dollar américain",
    UYU: "Peso uruguayen",
    UZS: "Sum ouzbek",
    VES: "Bolivar vénézuélien",
    VND: "Dong",
    VUV: "Vatu",
    WST: "Tala",
    XAF: "Franc centrafricain",
    XCD: "Dollar des Caraïbes orientales",
    XDR: "Droits de tirage spéciaux",
    XOF: "Franc ouest-africain",
    XPF: "Franc du Pacifique",
    YER: "Rial yéménite",
    ZAR: "Rand sudafricano",
    ZMW: "Kwacha zambien",
    ZWL: "Dollar zimbabuense",
  },
  de: {
    EUR: "Euro",
    AED: "Arabische Dirham",
    AFN: "Afghani",
    ALL: "Lek",
    AMD: "Dram",
    ANG: "Antillen Gulden",
    AOA: "Kwanza",
    ARS: "Argentinische Peso",
    AUD: "Australische Dollar",
    AWG: "Gulden",
    AZN: "Manat",
    BAM: "Konvertible Mark",
    BBD: "Barbados Dollar",
    BDT: "Taka",
    BGN: "Bulgarische Lew",
    BHD: "Bbahrainische Dinar",
    BIF: "Burundische Franc",
    BMD: "Bermudische Dollar",
    BND: "Brunei Dollar",
    BOB: "Boliviano",
    BRL: "Brasilianische Real",
    BSD: "Bahamas Dollar",
    BTN: "Ngultrum",
    BWP: "Pula",
    BYN: "Belarussische Rubel",
    BZD: "Belize Dollar",
    CAD: "Kanadische Dollar",
    CDF: "Kongolesische Franc",
    CHF: "Schweizer Franken",
    CLP: "Chilenische Peso",
    CNY: "Renminbi Yuan",
    COP: "Kolumbische Peso",
    CRC: "Colón",
    CUP: "Kubanische Peso",
    CVE: "Cap Verdische Escudo",
    CZK: "Tschechische Krone",
    DJF: "Dschibuti Franc",
    DKK: "Dänische Krone",
    DOP: "Dominikanische Peso",
    DZD: "Algerische Dinar",
    EGP: "Ägyptische Pfund",
    ERN: "Nakfa",
    ETB: "Birr",
    FJD: "Fidschi Dollar",
    FKP: "Falkländische Pfund",
    FOK: "Färöer Krone",
    GBP: "Sterling Pfund",
    GEL: "Georgische Lari",
    GGP: "Guernsey Pfund",
    GHS: "Ghanaische Cedi",
    GIP: "Gibraltar Pfund",
    GMD: "Dalasi",
    GNF: "Guinea Franc",
    GTQ: "Quetzal",
    GYD: "Guyana Dollar",
    HKD: "Hongkong Dollar",
    HNL: "Lempira",
    HRK: "Kuna",
    HTG: "Gourde",
    HUF: "Ungarische Forint",
    IDR: "Indonesische Rupiah",
    ILS: "Israelische Schekel",
    IMP: "Isle-of-Man Pfund",
    INR: "Indische Rupie",
    IQD: "Irakische Dinar",
    IRR: "Iranische Rial",
    ISK: "Isländische Krone",
    JEP: "Jersey Sterling Pfund",
    JMD: "Jamaikanische Dollar",
    JOD: "Jordanische Dinar",
    JPY: "Japanische Yen",
    KES: "Kenianische Schilling",
    KGS: "Som",
    KHR: "Kambodschanische Riel",
    KID: "Kiribati Dollar",
    KMF: "Komorische Franc",
    KRW: "Won",
    KWD: "Kuwaitische Dinar",
    KYD: "Cayman Dollar",
    KZT: "Tenge",
    LAK: "Kip",
    LBP: "Libanesische Pfund",
    LKR: "Sri Lanka Rupie",
    LRD: "Liberianische Dollar",
    LSL: "Lesothische Loti",
    LYD: "Libysche Dinar",
    MAD: "Marokkanische Dirham",
    MDL: "Leu",
    MGA: "Madagassische Ariary",
    MKD: "Mazedonische Denar",
    MMK: "Kyat",
    MNT: "Tögrög",
    MOP: "Macau Pataca",
    MRU: "Ouguiya",
    MUR: "Mauritius Rupie",
    MVR: "Maledivische Rufiyaa",
    MWK: "Kwacha",
    MXN: "Mexikanische Peso",
    MYR: "Ringgit",
    MZN: "Metical",
    NAD: "Namibische Dollar",
    NGN: "Naira",
    NIO: "Córdoba Oro",
    NOK: "Norwegische Krone",
    NPR: "Nepalesische Rupie",
    NZD: "Neuseeländische Dollar",
    OMR: "Omanische Rial",
    PAB: "Panamaische Balboa",
    PEN: "Nuevo Sol",
    PGK: "Kina",
    PHP: "Philippinische Peso",
    PKR: "Pakistanische Rupie",
    PLN: "Zloty",
    PYG: "Guaraní",
    QAR: "Qatar Rial",
    RON: "Leu",
    RSD: "Serbische Dinar",
    RUB: "Russische Rubel",
    RWF: "Ruandische Franc",
    SAR: "Saudische Rial",
    SBD: "Salomonische Dollar",
    SCR: "Seychellen Rupie",
    SDG: "Sudanesische Pfund",
    SEK: "Schwedische Krone",
    SGD: "Singapur Dollar",
    SHP: "St.-Helena Pfund",
    SLE: "Leone",
    SLL: "Leone",
    SOS: "Somalische Schilling",
    SRD: "Surinamische Dollar",
    SSP: "Südsudanesisches Pfund",
    STN: "São-toméischer Dobra",
    SYP: "Syrische Pfund",
    SZL: "Swazi Lilangeni",
    THB: "Thailändische Baht",
    TJS: "Somoni",
    TMT: "Manat",
    TND: "Tunesische Dinar",
    TOP: "Pa'anga",
    TRY: "Türkische Lira",
    TTD: "Trinidad und Tobago Dollar",
    TVD: "Tuvalu Dollar",
    TWD: "Taiwanesische Dollar",
    TZS: "Tansanische Schilling",
    UAH: "Hrywnja",
    UGX: "Ugandische Schilling",
    USD: "Amerikanische Dollar",
    UYU: "Uruguayische Peso",
    UZS: "Uzbekische So'm",
    VES: "Venezolanischer Bolívar",
    VND: "Dong",
    VUV: "Vatu",
    WST: "Tala",
    XAF: "Zentralafrikanische Franc",
    XCD: "Ostkaribische Dollar",
    XDR: "Sonderziehungsrecht",
    XOF: "Westafrikanische Franc",
    XPF: "Pazifische Franc",
    YER: "Jemenitische Rial",
    ZAR: "Südafrikanische Rand",
    ZMW: "Sambische Kwacha",
    ZWL: "Simbabwe Dollar",
  },
};
