// https://yarduon.com
export default {
  es: [
    "Restablecer configuración",
    "¿Quieres eliminar toda la información?",
    "Cancelar",
    "Eliminar",
    "Versión 1.1",
    "01/02/2023",
    "Se ha utilizado",
    "y",
    "No se ha encontrado un código QR en el archivo proporcionado",
    "El archivo proporcionado no es válido o ha sido corrompido",
  ],
  fr: [
    "Réinitialiser les paramètres",
    "Voulez-vous supprimer toutes les informations?",
    "Annuler",
    "Éliminer",
    "Version 1.1",
    "01/02/2023",
    "Ont été utilisés",
    "et",
    "Aucun code QR n'a été trouvé dans le fichier fourni",
    "Le fichier fourni n'est pas valide ou a été corrompu",
  ],
  de: [
    "Neu starten",
    "Möchten Sie alle Informationen löschen?",
    "Stornieren",
    "Löschen",
    "Version 1.1",
    "2023/02/01",
    "Wurden verwendet",
    "und",
    "Kein QR-Code in der angegebenen Datei gefunden",
    "Die zur Verfügung gestellte Datei ist ungültig oder wurde beschädigt",
  ],
};
