// https://yarduon.com
export default {
  es: [
    "Restablecer configuración",
    "¿Quieres eliminar toda la información?",
    "Cancelar",
    "Eliminar",
    "Versión 1.2",
    "29/09/2024",
    "Se ha utilizado",
    "y",
    "No se encontró un código QR en el archivo",
    "El archivo no es válido o está corrupto",
    "Cámara no disponible o permisos denegados",
  ],
  fr: [
    "Réinitialiser les paramètres",
    "Voulez-vous supprimer toutes les informations?",
    "Annuler",
    "Éliminer",
    "Version 1.2",
    "29/09/2024",
    "Ont été utilisés",
    "et",
    "Aucun code QR trouvé dans le fichier",
    "Le fichier est invalide ou corrompu",
    "Caméra indisponible ou autorisations bloquées",
  ],
  de: [
    "Neu starten",
    "Möchten Sie alle Informationen löschen?",
    "Stornieren",
    "Löschen",
    "Version 1.2",
    "2024/09/29",
    "Wurden verwendet",
    "und",
    "Kein QR-Code in der Datei gefunden",
    "Die Datei ist ungültig oder beschädigt",
    "Kamera nicht verfügbar oder verweigert",
  ],
};
